---
chdir: "/var/www/minesweeper/current"
environment: production
address: 0.0.0.0
port: 3001
timeout: 30
log: "/var/www/movies/current/log/thin.log"
pid: tmp/pids/thin2.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
daemonize: true
